import { ReportWithSections, BuildingSectionData, DashboardStats } from '@/types';

export const mockSections: BuildingSectionData[] = [
  {
    id: 'sec-1',
    reportId: 'report-1',
    category: 'vatrom',
    name: 'Baderom 1. etasje',
    conditionGrade: 'TG2',
    description: 'Baderommets flislagte gulv og vegger er i akseptabel stand, men det observeres tegn på fuktinntrengning.',
    observations: 'Fuktmålinger viser forhøyede verdier bak toalett og rundt dusjsone. Noen fliser har liten bevegelse ved trykktesting.',
    cause: 'Mangelfullt membransystem og slitt silikonfuge rundt dusjkabinett.',
    consequence: 'Fukt kan over tid trenge inn i underliggende konstruksjoner og forårsake råteskader og muggvekst.',
    repairCostMin: 35000,
    repairCostMax: 65000,
    sortOrder: 1,
    isRequired: true,
  },
  {
    id: 'sec-2',
    reportId: 'report-1',
    category: 'tak',
    name: 'Tak og takkonstruksjon',
    conditionGrade: 'TG1',
    description: 'Takkonstruksjonen er i god teknisk stand med normal slitasje for alder.',
    observations: 'Taktekkingen fremstår hel og uten synlige skader. Renner og nedløp er rene og fungerer som de skal.',
    sortOrder: 2,
    isRequired: true,
  },
  {
    id: 'sec-3',
    reportId: 'report-1',
    category: 'elektrisk',
    name: 'Elektrisk anlegg',
    conditionGrade: 'TG2',
    description: 'Det elektriske anlegget er delvis modernisert, men har elementer som ikke tilfredsstiller dagens krav.',
    observations: 'Sikringsskapet er av eldre type med skrusikringer. Deler av anlegget mangler jordingskontakter.',
    cause: 'Anlegget er ikke fullt ut modernisert og mangler nødvendig oppdatering.',
    consequence: 'Økt risiko for elektriske feil og brann. Tilfredsstiller ikke NEK 400 fullt ut.',
    repairCostMin: 25000,
    repairCostMax: 45000,
    sortOrder: 3,
    isRequired: true,
  },
];

export const mockReports: ReportWithSections[] = [
  {
    id: 'report-1',
    userId: 'user-1',
    reportNumber: 'TR-2025-0042',
    type: 'tilstandsrapport',
    status: 'completed',
    propertyAddress: 'Storgata 15',
    postalCode: '0184',
    city: 'Oslo',
    municipality: 'Oslo',
    gnr: '207',
    bnr: '134',
    propertyType: 'enebolig',
    constructionYear: 1987,
    bra: 185,
    prom: 162,
    numberOfFloors: 2,
    client: 'Kari Nordmann',
    clientEmail: 'kari@example.com',
    clientPhone: '+47 900 12 345',
    inspectionDate: new Date('2025-11-15').toISOString(),
    reportDate: new Date('2025-11-20').toISOString(),
    marketValue: 6500000,
    loanValue: 5500000,
    technicalValue: 5800000,
    totalRepairCost: 110000,
    summary: 'Boligen fremstår i generelt god stand for sin alder. Det er registrert to TG2-avvik på baderom og elektrisk anlegg som bør utbedres i nær fremtid.',
    createdAt: new Date('2025-11-15').toISOString(),
    updatedAt: new Date('2025-11-20').toISOString(),
    sections: mockSections,
  },
  {
    id: 'report-2',
    userId: 'user-1',
    reportNumber: 'TR-2025-0041',
    type: 'verditakst',
    status: 'completed',
    propertyAddress: 'Parkveien 8B',
    postalCode: '0350',
    city: 'Oslo',
    municipality: 'Oslo',
    gnr: '212',
    bnr: '45',
    propertyType: 'leilighet',
    constructionYear: 2005,
    bra: 78,
    prom: 72,
    numberOfFloors: 1,
    client: 'Per Hansen',
    clientEmail: 'per@example.com',
    inspectionDate: new Date('2025-11-10').toISOString(),
    reportDate: new Date('2025-11-13').toISOString(),
    marketValue: 4200000,
    loanValue: 3800000,
    totalRepairCost: 15000,
    summary: 'Leiligheten fremstår i god stand med normal slitasje.',
    createdAt: new Date('2025-11-10').toISOString(),
    updatedAt: new Date('2025-11-13').toISOString(),
    sections: [],
  },
  {
    id: 'report-3',
    userId: 'user-1',
    reportNumber: 'TR-2025-0043',
    type: 'tilstandsrapport',
    status: 'in_progress',
    propertyAddress: 'Bjørnveien 3',
    postalCode: '1344',
    city: 'Haslum',
    municipality: 'Bærum',
    gnr: '18',
    bnr: '92',
    propertyType: 'tomannsbolig',
    constructionYear: 1965,
    bra: 210,
    prom: 185,
    numberOfFloors: 2,
    client: 'Anne Olsen',
    inspectionDate: new Date('2025-11-22').toISOString(),
    createdAt: new Date('2025-11-22').toISOString(),
    updatedAt: new Date('2025-11-22').toISOString(),
    sections: [],
  },
  {
    id: 'report-4',
    userId: 'user-1',
    reportNumber: 'TR-2025-0044',
    type: 'tilstandsrapport',
    status: 'draft',
    propertyAddress: 'Granveien 22',
    postalCode: '1400',
    city: 'Ski',
    municipality: 'Nordre Follo',
    propertyType: 'enebolig',
    constructionYear: 1978,
    bra: 145,
    createdAt: new Date('2025-11-25').toISOString(),
    updatedAt: new Date('2025-11-25').toISOString(),
    sections: [],
  },
  {
    id: 'report-5',
    userId: 'user-1',
    reportNumber: 'TR-2025-0039',
    type: 'forhandstakst',
    status: 'archived',
    propertyAddress: 'Havnepromenaden 7',
    postalCode: '0252',
    city: 'Oslo',
    municipality: 'Oslo',
    propertyType: 'leilighet',
    constructionYear: 2020,
    bra: 95,
    client: 'Lars Berg',
    inspectionDate: new Date('2025-10-28').toISOString(),
    reportDate: new Date('2025-11-01').toISOString(),
    marketValue: 7800000,
    totalRepairCost: 0,
    createdAt: new Date('2025-10-28').toISOString(),
    updatedAt: new Date('2025-11-01').toISOString(),
    sections: [],
  },
];

export const mockDashboardStats: DashboardStats = {
  totalReports: 44,
  completedThisMonth: 8,
  inProgress: 3,
  avgTGDistribution: {
    TG0: 12,
    TG1: 45,
    TG2: 28,
    TG3: 8,
    TGIU: 7,
  },
};

export const mockUser = {
  id: 'user-1',
  name: 'Erik Johnsen',
  email: 'erik@takstfirma.no',
  company: 'Johnsen Takst AS',
  phone: '+47 900 00 000',
  certifications: 'Statsautorisert takstmann, NITO Takst',
};
